// Curated emoji catalog with Portuguese (pt-BR) names.
// Covers Unicode ranges referenced in the spec (Smileys, Symbols & Pictographs,
// Supplemental Symbols, Transport & Map, etc.) but limited to emojis whose
// silhouette/shape is recognizable enough to be guessable when pixelated.
// The frontend never receives the day's emoji — this list is also used to
// power autocomplete, so PT-BR names act as alternative answers.

export type EmojiEntry = {
  emoji: string;
  name: string; // canonical pt-BR name
  aliases?: string[]; // accepted alternate spellings/synonyms
};

export const EMOJIS: EmojiEntry[] = [
  // --- Smileys & emotion ---
  { emoji: "😀", name: "rosto sorrindo", aliases: ["sorriso", "feliz"] },
  { emoji: "😂", name: "rosto chorando de rir", aliases: ["chorando de rir", "rindo"] },
  { emoji: "🤣", name: "rolando de rir", aliases: ["rolando no chao"] },
  { emoji: "😍", name: "rosto apaixonado", aliases: ["apaixonado", "olhos de coracao"] },
  { emoji: "😎", name: "rosto com oculos escuros", aliases: ["oculos escuros", "estiloso"] },
  { emoji: "😭", name: "rosto chorando muito", aliases: ["chorando", "choro"] },
  { emoji: "😡", name: "rosto bravo", aliases: ["bravo", "irritado", "raiva"] },
  { emoji: "😱", name: "rosto gritando de medo", aliases: ["assustado", "medo"] },
  { emoji: "🥺", name: "rosto suplicante", aliases: ["suplicante", "pidao"] },
  { emoji: "😴", name: "rosto dormindo", aliases: ["dormindo", "sono"] },
  { emoji: "🤔", name: "rosto pensativo", aliases: ["pensando"] },
  { emoji: "🤯", name: "explosao mental", aliases: ["mente explodindo"] },
  { emoji: "🥳", name: "rosto festivo", aliases: ["festa", "comemorando"] },
  { emoji: "😇", name: "rosto com aureola", aliases: ["anjo"] },
  { emoji: "😈", name: "diabinho sorrindo", aliases: ["diabinho", "diabo"] },
  { emoji: "🤡", name: "palhaco", aliases: ["clown"] },
  { emoji: "👻", name: "fantasma", aliases: ["assombracao"] },
  { emoji: "💀", name: "caveira", aliases: ["cranio"] },
  { emoji: "👽", name: "alienigena", aliases: ["et"] },
  { emoji: "🤖", name: "robo", aliases: ["robot"] },
  { emoji: "💩", name: "coco", aliases: ["coco sorridente", "merda"] },
  { emoji: "👹", name: "ogro", aliases: [] },
  { emoji: "👺", name: "duende", aliases: [] },
  { emoji: "😅", name: "rosto suando", aliases: ["alivio", "ufa"] },
  { emoji: "😉", name: "rosto piscando", aliases: ["piscadinha"] },
  { emoji: "😘", name: "mandando beijo", aliases: ["beijinho", "beijo"] },
  { emoji: "😋", name: "rosto saboreando", aliases: ["delicioso", "gostoso"] },
  { emoji: "😜", name: "lingua de fora", aliases: ["lingua para fora"] },
  { emoji: "🥰", name: "rosto com coracoes", aliases: ["amando", "encantado"] },
  { emoji: "🤩", name: "rosto deslumbrado", aliases: ["olhos de estrela", "uau"] },
  { emoji: "🥶", name: "rosto congelando", aliases: ["congelando", "frio"] },
  { emoji: "🥵", name: "rosto suando de calor", aliases: ["calor"] },
  { emoji: "😷", name: "rosto com mascara", aliases: ["mascara"] },
  { emoji: "🤒", name: "rosto doente", aliases: ["doente", "termometro"] },
  { emoji: "🤧", name: "rosto espirrando", aliases: ["espirro", "gripado"] },
  { emoji: "🤫", name: "rosto silencioso", aliases: ["shh", "silencio"] },
  { emoji: "🤓", name: "rosto de nerd", aliases: ["nerd", "estudioso"] },
  { emoji: "🥱", name: "rosto bocejando", aliases: ["bocejo", "sonolento"] },
  { emoji: "😬", name: "rosto sem graca", aliases: ["careta"] },
  { emoji: "🤐", name: "boca fechada com ziper", aliases: ["boca trancada"] },

  // --- Hand & people ---
  { emoji: "👋", name: "aceno", aliases: ["mao acenando", "tchau"] },
  { emoji: "👍", name: "joinha", aliases: ["polegar para cima", "curtir"] },
  { emoji: "👎", name: "polegar para baixo", aliases: ["descurtir"] },
  { emoji: "👏", name: "palmas", aliases: ["aplausos"] },
  { emoji: "🙏", name: "maos juntas", aliases: ["oracao", "obrigado"] },
  { emoji: "💪", name: "biceps", aliases: ["forca", "musculo"] },
  { emoji: "🤝", name: "aperto de mao", aliases: ["acordo"] },
  { emoji: "✌️", name: "sinal de paz", aliases: ["paz e amor"] },
  { emoji: "🤘", name: "rock", aliases: ["chifre"] },
  { emoji: "👀", name: "olhos", aliases: ["olhando"] },
  { emoji: "👶", name: "bebe", aliases: ["neném"] },
  { emoji: "👴", name: "velhinho", aliases: ["idoso", "vovo"] },
  { emoji: "👵", name: "velhinha", aliases: ["idosa", "vovó"] },
  { emoji: "👮", name: "policial", aliases: [] },
  { emoji: "👷", name: "operario", aliases: ["trabalhador"] },
  { emoji: "🧙", name: "mago", aliases: ["bruxo"] },
  { emoji: "🧛", name: "vampiro", aliases: [] },
  { emoji: "🧜", name: "sereia", aliases: [] },
  { emoji: "🧚", name: "fada", aliases: [] },
  { emoji: "🦸", name: "super heroi", aliases: ["heroi"] },
  { emoji: "🎅", name: "papai noel", aliases: ["noel"] },
  { emoji: "👸", name: "princesa", aliases: [] },
  { emoji: "🤴", name: "principe", aliases: [] },
  { emoji: "👌", name: "ok com a mao", aliases: ["ok", "joia"] },
  { emoji: "🤞", name: "dedos cruzados", aliases: ["torcendo", "torcida"] },
  { emoji: "🤙", name: "shaka", aliases: ["me liga", "hang loose"] },
  { emoji: "👊", name: "soquinho", aliases: ["soco", "punho fechado"] },
  { emoji: "🧠", name: "cerebro", aliases: ["miolo"] },
  { emoji: "👅", name: "lingua", aliases: [] },
  { emoji: "👄", name: "boca", aliases: ["labios"] },
  { emoji: "👃", name: "nariz", aliases: [] },
  { emoji: "👂", name: "orelha", aliases: ["ouvido"] },
  { emoji: "👼", name: "bebe anjo", aliases: ["anjinho"] },
  { emoji: "🧟", name: "zumbi", aliases: ["morto vivo"] },
  { emoji: "🧞", name: "genio da lampada", aliases: ["genio"] },
  { emoji: "🦹", name: "vilao", aliases: ["super vilao"] },

  // --- Animals ---
  { emoji: "🐶", name: "cachorro", aliases: ["dog", "doguinho", "filhote"] },
  { emoji: "🐱", name: "gato", aliases: ["gatinho", "cat"] },
  { emoji: "🐭", name: "rato", aliases: ["camundongo"] },
  { emoji: "🐹", name: "hamster", aliases: [] },
  { emoji: "🐰", name: "coelho", aliases: ["coelhinho"] },
  { emoji: "🦊", name: "raposa", aliases: [] },
  { emoji: "🐻", name: "urso", aliases: [] },
  { emoji: "🐼", name: "panda", aliases: ["urso panda"] },
  { emoji: "🐨", name: "coala", aliases: [] },
  { emoji: "🐯", name: "tigre", aliases: [] },
  { emoji: "🦁", name: "leao", aliases: [] },
  { emoji: "🐮", name: "vaca", aliases: ["boi"] },
  { emoji: "🐷", name: "porco", aliases: ["porquinho"] },
  { emoji: "🐸", name: "sapo", aliases: ["ra"] },
  { emoji: "🐵", name: "macaco", aliases: ["mico"] },
  { emoji: "🙈", name: "macaco nao ver", aliases: [] },
  { emoji: "🐔", name: "galinha", aliases: [] },
  { emoji: "🐧", name: "pinguim", aliases: [] },
  { emoji: "🐦", name: "passaro", aliases: ["passarinho"] },
  { emoji: "🦅", name: "aguia", aliases: [] },
  { emoji: "🦆", name: "pato", aliases: [] },
  { emoji: "🦉", name: "coruja", aliases: [] },
  { emoji: "🦇", name: "morcego", aliases: [] },
  { emoji: "🐺", name: "lobo", aliases: [] },
  { emoji: "🐗", name: "javali", aliases: [] },
  { emoji: "🐴", name: "cavalo", aliases: ["cavalinho"] },
  { emoji: "🦄", name: "unicornio", aliases: [] },
  { emoji: "🐝", name: "abelha", aliases: [] },
  { emoji: "🐛", name: "lagarta", aliases: ["minhoca"] },
  { emoji: "🦋", name: "borboleta", aliases: [] },
  { emoji: "🐌", name: "lesma", aliases: ["caracol"] },
  { emoji: "🐞", name: "joaninha", aliases: [] },
  { emoji: "🐢", name: "tartaruga", aliases: [] },
  { emoji: "🐍", name: "cobra", aliases: ["serpente"] },
  { emoji: "🦂", name: "escorpiao", aliases: [] },
  { emoji: "🐙", name: "polvo", aliases: [] },
  { emoji: "🦑", name: "lula", aliases: [] },
  { emoji: "🦐", name: "camarao", aliases: [] },
  { emoji: "🦀", name: "caranguejo", aliases: [] },
  { emoji: "🐠", name: "peixe tropical", aliases: ["peixe"] },
  { emoji: "🐬", name: "golfinho", aliases: [] },
  { emoji: "🐳", name: "baleia", aliases: [] },
  { emoji: "🦈", name: "tubarao", aliases: [] },
  { emoji: "🐊", name: "crocodilo", aliases: ["jacare"] },
  { emoji: "🐅", name: "tigre completo", aliases: [] },
  { emoji: "🐆", name: "leopardo", aliases: ["onca"] },
  { emoji: "🦓", name: "zebra", aliases: [] },
  { emoji: "🦍", name: "gorila", aliases: [] },
  { emoji: "🐘", name: "elefante", aliases: [] },
  { emoji: "🦏", name: "rinoceronte", aliases: [] },
  { emoji: "🦛", name: "hipopotamo", aliases: [] },
  { emoji: "🐪", name: "camelo", aliases: [] },
  { emoji: "🐫", name: "dromedario", aliases: [] },
  { emoji: "🦒", name: "girafa", aliases: [] },
  { emoji: "🦘", name: "canguru", aliases: [] },
  { emoji: "🐃", name: "bufalo", aliases: [] },
  { emoji: "🐎", name: "cavalo correndo", aliases: [] },
  { emoji: "🐑", name: "ovelha", aliases: [] },
  { emoji: "🐐", name: "cabra", aliases: ["bode"] },
  { emoji: "🦙", name: "lhama", aliases: [] },
  { emoji: "🦌", name: "cervo", aliases: ["veado"] },
  { emoji: "🐕", name: "cachorro de lado", aliases: [] },
  { emoji: "🐩", name: "poodle", aliases: [] },
  { emoji: "🦮", name: "cao guia", aliases: [] },
  { emoji: "🐈", name: "gato de lado", aliases: [] },
  { emoji: "🐓", name: "galo", aliases: [] },
  { emoji: "🦃", name: "peru", aliases: [] },
  { emoji: "🦚", name: "pavao", aliases: [] },
  { emoji: "🦜", name: "papagaio", aliases: [] },
  { emoji: "🦢", name: "cisne", aliases: [] },
  { emoji: "🦩", name: "flamingo", aliases: [] },
  { emoji: "🐇", name: "coelho de lado", aliases: [] },
  { emoji: "🐿️", name: "esquilo", aliases: [] },
  { emoji: "🦔", name: "ourico", aliases: [] },
  { emoji: "🐉", name: "dragao", aliases: [] },
  { emoji: "🦖", name: "tiranossauro", aliases: ["t-rex"] },
  { emoji: "🦕", name: "dinossauro", aliases: ["brontossauro"] },
  { emoji: "🐲", name: "rosto de dragao", aliases: ["dragao chines"] },
  { emoji: "🦦", name: "lontra", aliases: [] },
  { emoji: "🦥", name: "preguica", aliases: ["bicho preguica"] },
  { emoji: "🦨", name: "gamba", aliases: ["jaratataca"] },
  { emoji: "🐂", name: "touro", aliases: [] },
  { emoji: "🐡", name: "baiacu", aliases: ["peixe balao"] },
  { emoji: "🐟", name: "peixe", aliases: [] },
  { emoji: "🦫", name: "castor", aliases: [] },

  // --- Plants & nature ---
  { emoji: "🌵", name: "cacto", aliases: [] },
  { emoji: "🌲", name: "pinheiro", aliases: [] },
  { emoji: "🌳", name: "arvore", aliases: [] },
  { emoji: "🌴", name: "coqueiro", aliases: ["palmeira"] },
  { emoji: "🌱", name: "muda", aliases: ["broto"] },
  { emoji: "🌿", name: "erva", aliases: ["folhas"] },
  { emoji: "🍀", name: "trevo", aliases: ["quatro folhas", "sorte"] },
  { emoji: "🍃", name: "folha ao vento", aliases: ["folhas"] },
  { emoji: "🍂", name: "folha de outono", aliases: [] },
  { emoji: "🍁", name: "folha de bordo", aliases: [] },
  { emoji: "🌷", name: "tulipa", aliases: [] },
  { emoji: "🌹", name: "rosa", aliases: [] },
  { emoji: "🌻", name: "girassol", aliases: [] },
  { emoji: "🌼", name: "margarida", aliases: [] },
  { emoji: "🌸", name: "flor de cerejeira", aliases: ["sakura"] },
  { emoji: "💐", name: "buque", aliases: ["flores"] },
  { emoji: "🌎", name: "globo americas", aliases: ["mundo", "terra"] },
  { emoji: "🌋", name: "vulcao", aliases: [] },
  { emoji: "🏔️", name: "montanha nevada", aliases: [] },
  { emoji: "⛰️", name: "montanha", aliases: [] },
  { emoji: "🏖️", name: "praia", aliases: [] },
  { emoji: "🏝️", name: "ilha", aliases: [] },
  { emoji: "🌊", name: "onda", aliases: ["mar"] },
  { emoji: "🌺", name: "hibisco", aliases: [] },
  { emoji: "🪴", name: "planta em vaso", aliases: ["vaso de planta"] },
  { emoji: "🌾", name: "espigas", aliases: ["trigo", "arroz em pe"] },
  { emoji: "🪨", name: "pedra", aliases: ["rocha"] },
  { emoji: "🪵", name: "tora de madeira", aliases: ["tronco"] },
  { emoji: "🌍", name: "globo terrestre africa", aliases: ["mundo africa"] },
  { emoji: "🌏", name: "globo terrestre asia", aliases: ["mundo asia"] },
  { emoji: "🏜️", name: "deserto", aliases: [] },
  { emoji: "🏕️", name: "acampamento", aliases: ["camping"] },

  // --- Sky & weather ---
  { emoji: "☀️", name: "sol", aliases: [] },
  { emoji: "🌙", name: "lua crescente", aliases: ["lua"] },
  { emoji: "⭐", name: "estrela", aliases: [] },
  { emoji: "🌟", name: "estrela brilhante", aliases: [] },
  { emoji: "✨", name: "brilhos", aliases: ["estrelinhas"] },
  { emoji: "⚡", name: "raio", aliases: ["relampago"] },
  { emoji: "🔥", name: "fogo", aliases: ["chama"] },
  { emoji: "💧", name: "gota", aliases: ["agua"] },
  { emoji: "🌈", name: "arco iris", aliases: [] },
  { emoji: "☁️", name: "nuvem", aliases: [] },
  { emoji: "❄️", name: "floco de neve", aliases: ["neve"] },
  { emoji: "☃️", name: "boneco de neve", aliases: [] },
  { emoji: "⛄", name: "boneco de neve sem neve", aliases: [] },
  { emoji: "🌪️", name: "tornado", aliases: [] },
  { emoji: "🌞", name: "sol com rosto", aliases: [] },
  { emoji: "🌝", name: "lua cheia com rosto", aliases: ["lua cheia"] },
  { emoji: "🌚", name: "lua nova com rosto", aliases: [] },
  { emoji: "🌧️", name: "nuvem com chuva", aliases: ["chuva"] },
  { emoji: "⛈️", name: "tempestade", aliases: ["raios e chuva"] },
  { emoji: "🌫️", name: "neblina", aliases: ["nevoeiro"] },
  { emoji: "☔", name: "guarda chuva com chuva", aliases: ["chuva guarda chuva"] },
  { emoji: "☂️", name: "guarda chuva", aliases: ["sombrinha"] },
  { emoji: "🪐", name: "planeta com aneis", aliases: ["saturno"] },
  { emoji: "☄️", name: "cometa", aliases: [] },
  { emoji: "🌠", name: "estrela cadente", aliases: [] },

  // --- Food & drinks ---
  { emoji: "🍎", name: "maca", aliases: [] },
  { emoji: "🍌", name: "banana", aliases: [] },
  { emoji: "🍇", name: "uva", aliases: [] },
  { emoji: "🍓", name: "morango", aliases: [] },
  { emoji: "🍉", name: "melancia", aliases: [] },
  { emoji: "🍊", name: "laranja", aliases: ["tangerina"] },
  { emoji: "🍋", name: "limao", aliases: [] },
  { emoji: "🍑", name: "pessego", aliases: [] },
  { emoji: "🍒", name: "cereja", aliases: ["cerejas"] },
  { emoji: "🍍", name: "abacaxi", aliases: [] },
  { emoji: "🥭", name: "manga", aliases: [] },
  { emoji: "🥥", name: "coco", aliases: [] },
  { emoji: "🥝", name: "kiwi", aliases: [] },
  { emoji: "🍅", name: "tomate", aliases: [] },
  { emoji: "🥑", name: "abacate", aliases: [] },
  { emoji: "🌽", name: "milho", aliases: [] },
  { emoji: "🥕", name: "cenoura", aliases: [] },
  { emoji: "🥒", name: "pepino", aliases: [] },
  { emoji: "🌶️", name: "pimenta", aliases: [] },
  { emoji: "🍄", name: "cogumelo", aliases: [] },
  { emoji: "🥜", name: "amendoim", aliases: [] },
  { emoji: "🌰", name: "castanha", aliases: [] },
  { emoji: "🍞", name: "pao", aliases: [] },
  { emoji: "🥐", name: "croissant", aliases: [] },
  { emoji: "🥖", name: "baguete", aliases: [] },
  { emoji: "🥨", name: "pretzel", aliases: [] },
  { emoji: "🧀", name: "queijo", aliases: [] },
  { emoji: "🥚", name: "ovo", aliases: [] },
  { emoji: "🍳", name: "ovo frito", aliases: [] },
  { emoji: "🥞", name: "panqueca", aliases: [] },
  { emoji: "🥓", name: "bacon", aliases: [] },
  { emoji: "🍔", name: "hamburguer", aliases: [] },
  { emoji: "🍟", name: "batata frita", aliases: [] },
  { emoji: "🍕", name: "pizza", aliases: [] },
  { emoji: "🌭", name: "cachorro quente", aliases: ["hot dog"] },
  { emoji: "🥪", name: "sanduiche", aliases: [] },
  { emoji: "🌮", name: "taco", aliases: [] },
  { emoji: "🌯", name: "burrito", aliases: [] },
  { emoji: "🥗", name: "salada", aliases: [] },
  { emoji: "🍝", name: "espaguete", aliases: ["macarrao"] },
  { emoji: "🍜", name: "lamen", aliases: ["sopa"] },
  { emoji: "🍣", name: "sushi", aliases: [] },
  { emoji: "🍱", name: "marmita", aliases: ["bento"] },
  { emoji: "🍤", name: "tempura", aliases: ["camarao frito"] },
  { emoji: "🍙", name: "bolinho de arroz", aliases: ["onigiri"] },
  { emoji: "🍚", name: "tigela de arroz", aliases: ["arroz"] },
  { emoji: "🍩", name: "rosquinha", aliases: ["donut"] },
  { emoji: "🍪", name: "biscoito", aliases: [] },
  { emoji: "🎂", name: "bolo de aniversario", aliases: ["bolo"] },
  { emoji: "🍰", name: "fatia de bolo", aliases: [] },
  { emoji: "🧁", name: "cupcake", aliases: [] },
  { emoji: "🍫", name: "chocolate", aliases: [] },
  { emoji: "🍬", name: "bala", aliases: ["doce"] },
  { emoji: "🍭", name: "pirulito", aliases: [] },
  { emoji: "🍮", name: "pudim", aliases: [] },
  { emoji: "🍯", name: "mel", aliases: [] },
  { emoji: "🍦", name: "sorvete", aliases: ["casquinha"] },
  { emoji: "🍧", name: "raspadinha", aliases: [] },
  { emoji: "🍨", name: "sundae", aliases: [] },
  { emoji: "🍿", name: "pipoca", aliases: [] },
  { emoji: "🥛", name: "copo de leite", aliases: ["leite"] },
  { emoji: "☕", name: "cafe", aliases: ["xicara"] },
  { emoji: "🍵", name: "cha", aliases: [] },
  { emoji: "🍺", name: "cerveja", aliases: [] },
  { emoji: "🍷", name: "vinho", aliases: ["taca de vinho"] },
  { emoji: "🥂", name: "brinde", aliases: [] },
  { emoji: "🍹", name: "drink tropical", aliases: [] },
  { emoji: "🍸", name: "martini", aliases: ["coquetel"] },
  { emoji: "🥤", name: "refrigerante", aliases: ["copo com canudo"] },
  { emoji: "🍐", name: "pera", aliases: [] },
  { emoji: "🍈", name: "melao", aliases: [] },
  { emoji: "🫐", name: "mirtilo", aliases: ["blueberry"] },
  { emoji: "🫒", name: "azeitona", aliases: [] },
  { emoji: "🥬", name: "verdura folhosa", aliases: ["alface", "repolho"] },
  { emoji: "🥦", name: "brocolis", aliases: [] },
  { emoji: "🧅", name: "cebola", aliases: [] },
  { emoji: "🧄", name: "alho", aliases: [] },
  { emoji: "🥯", name: "bagel", aliases: ["rosca de pao"] },
  { emoji: "🧇", name: "waffle", aliases: [] },
  { emoji: "🥧", name: "torta", aliases: [] },
  { emoji: "🦞", name: "lagosta", aliases: [] },
  { emoji: "🍶", name: "sake", aliases: ["garrafa japonesa"] },
  { emoji: "🥃", name: "copo baixo", aliases: ["uisque", "whisky"] },
  { emoji: "🍻", name: "canecas de cerveja", aliases: ["brindando"] },

  // --- Travel & places ---
  { emoji: "🚗", name: "carro", aliases: [] },
  { emoji: "🚕", name: "taxi", aliases: [] },
  { emoji: "🚙", name: "suv", aliases: [] },
  { emoji: "🚌", name: "onibus", aliases: [] },
  { emoji: "🏎️", name: "carro de corrida", aliases: [] },
  { emoji: "🚓", name: "viatura", aliases: [] },
  { emoji: "🚑", name: "ambulancia", aliases: [] },
  { emoji: "🚒", name: "caminhao de bombeiro", aliases: [] },
  { emoji: "🚐", name: "van", aliases: [] },
  { emoji: "🚚", name: "caminhao", aliases: [] },
  { emoji: "🚜", name: "trator", aliases: [] },
  { emoji: "🏍️", name: "moto", aliases: [] },
  { emoji: "🚲", name: "bicicleta", aliases: [] },
  { emoji: "🛴", name: "patinete", aliases: [] },
  { emoji: "🛹", name: "skate", aliases: [] },
  { emoji: "✈️", name: "aviao", aliases: [] },
  { emoji: "🚀", name: "foguete", aliases: [] },
  { emoji: "🛸", name: "disco voador", aliases: ["ovni"] },
  { emoji: "🚁", name: "helicoptero", aliases: [] },
  { emoji: "⛵", name: "veleiro", aliases: ["barco"] },
  { emoji: "🚤", name: "lancha", aliases: [] },
  { emoji: "🚢", name: "navio", aliases: [] },
  { emoji: "🚂", name: "locomotiva", aliases: ["trem"] },
  { emoji: "🚆", name: "trem", aliases: [] },
  { emoji: "🛵", name: "lambreta", aliases: ["scooter"] },
  { emoji: "🏠", name: "casa", aliases: [] },
  { emoji: "🏰", name: "castelo", aliases: [] },
  { emoji: "🗼", name: "torre de toquio", aliases: ["torre"] },
  { emoji: "🗽", name: "estatua da liberdade", aliases: [] },
  { emoji: "🗿", name: "moai", aliases: [] },
  { emoji: "🌉", name: "ponte", aliases: [] },
  { emoji: "🎡", name: "roda gigante", aliases: [] },
  { emoji: "🎢", name: "montanha russa", aliases: [] },
  { emoji: "🎠", name: "carrossel", aliases: [] },
  { emoji: "⛩️", name: "torii", aliases: [] },
  { emoji: "🕌", name: "mesquita", aliases: [] },
  { emoji: "⛪", name: "igreja", aliases: [] },
  { emoji: "🚇", name: "metro", aliases: ["subway"] },
  { emoji: "🚊", name: "bonde", aliases: ["vlt"] },
  { emoji: "🛻", name: "caminhonete", aliases: ["pickup"] },
  { emoji: "🛺", name: "tuk tuk", aliases: ["motoriquixa"] },
  { emoji: "🚏", name: "parada de onibus", aliases: ["ponto de onibus"] },
  { emoji: "🏟️", name: "estadio", aliases: [] },
  { emoji: "🏥", name: "hospital", aliases: [] },
  { emoji: "🏦", name: "banco", aliases: [] },
  { emoji: "🏫", name: "escola", aliases: [] },
  { emoji: "🏭", name: "fabrica", aliases: [] },
  { emoji: "🏯", name: "castelo japones", aliases: [] },
  { emoji: "🗻", name: "monte fuji", aliases: ["fuji"] },

  // --- Sports & activities ---
  { emoji: "⚽", name: "bola de futebol", aliases: ["futebol"] },
  { emoji: "🏀", name: "bola de basquete", aliases: ["basquete"] },
  { emoji: "🏈", name: "futebol americano", aliases: [] },
  { emoji: "⚾", name: "beisebol", aliases: [] },
  { emoji: "🎾", name: "tenis", aliases: [] },
  { emoji: "🏐", name: "volei", aliases: [] },
  { emoji: "🏓", name: "tenis de mesa", aliases: ["pingue pongue"] },
  { emoji: "🏸", name: "badminton", aliases: [] },
  { emoji: "🥊", name: "luva de boxe", aliases: ["boxe"] },
  { emoji: "🎯", name: "alvo", aliases: [] },
  { emoji: "🎲", name: "dado", aliases: [] },
  { emoji: "🎳", name: "boliche", aliases: [] },
  { emoji: "🎮", name: "controle de video game", aliases: ["controle", "videogame"] },
  { emoji: "🕹️", name: "joystick", aliases: [] },
  { emoji: "🎰", name: "caca niquel", aliases: [] },
  { emoji: "🧩", name: "quebra cabeca", aliases: [] },
  { emoji: "🎱", name: "bola 8", aliases: ["sinuca"] },
  { emoji: "🏆", name: "trofeu", aliases: [] },
  { emoji: "🏅", name: "medalha", aliases: [] },
  { emoji: "🥇", name: "medalha de ouro", aliases: [] },
  { emoji: "🥈", name: "medalha de prata", aliases: [] },
  { emoji: "🥉", name: "medalha de bronze", aliases: [] },
  { emoji: "🏹", name: "arco e flecha", aliases: ["arqueiro"] },
  { emoji: "🥋", name: "kimono", aliases: ["judo"] },
  { emoji: "⛳", name: "bandeira de golfe", aliases: ["golfe"] },
  { emoji: "🪂", name: "paraquedas", aliases: ["paraquedismo"] },
  { emoji: "⛸️", name: "patim de gelo", aliases: ["patinacao no gelo"] },
  { emoji: "🛼", name: "patins de roda", aliases: ["patins"] },
  { emoji: "🤿", name: "mascara de mergulho", aliases: ["mergulho"] },

  // --- Objects & misc ---
  { emoji: "📱", name: "celular", aliases: ["smartphone"] },
  { emoji: "💻", name: "notebook", aliases: ["laptop"] },
  { emoji: "🖥️", name: "computador", aliases: [] },
  { emoji: "🖱️", name: "mouse", aliases: [] },
  { emoji: "⌨️", name: "teclado", aliases: [] },
  { emoji: "📷", name: "camera", aliases: [] },
  { emoji: "🎥", name: "filmadora", aliases: ["camera de cinema"] },
  { emoji: "📺", name: "televisao", aliases: ["tv"] },
  { emoji: "📻", name: "radio", aliases: [] },
  { emoji: "🎙️", name: "microfone", aliases: [] },
  { emoji: "🎧", name: "fone de ouvido", aliases: [] },
  { emoji: "🎸", name: "guitarra", aliases: ["violao"] },
  { emoji: "🎹", name: "piano", aliases: ["teclado musical"] },
  { emoji: "🥁", name: "bateria", aliases: ["tambor"] },
  { emoji: "🎺", name: "trompete", aliases: [] },
  { emoji: "🎷", name: "saxofone", aliases: [] },
  { emoji: "🎻", name: "violino", aliases: [] },
  { emoji: "🎬", name: "claquete", aliases: ["acao"] },
  { emoji: "🎤", name: "microfone de show", aliases: [] },
  { emoji: "📚", name: "livros", aliases: [] },
  { emoji: "📖", name: "livro aberto", aliases: [] },
  { emoji: "📒", name: "caderno", aliases: [] },
  { emoji: "📝", name: "anotacao", aliases: ["bloco de notas"] },
  { emoji: "✏️", name: "lapis", aliases: [] },
  { emoji: "🖊️", name: "caneta", aliases: [] },
  { emoji: "✂️", name: "tesoura", aliases: [] },
  { emoji: "📌", name: "tachinha", aliases: [] },
  { emoji: "📎", name: "clipe de papel", aliases: ["clipe"] },
  { emoji: "🔒", name: "cadeado", aliases: ["fechado"] },
  { emoji: "🔑", name: "chave", aliases: [] },
  { emoji: "🔨", name: "martelo", aliases: [] },
  { emoji: "🔧", name: "chave de boca", aliases: [] },
  { emoji: "🪓", name: "machado", aliases: [] },
  { emoji: "⚙️", name: "engrenagem", aliases: [] },
  { emoji: "💡", name: "lampada", aliases: ["ideia"] },
  { emoji: "🔋", name: "bateria de pilha", aliases: ["pilha"] },
  { emoji: "🔌", name: "tomada", aliases: ["plug"] },
  { emoji: "💎", name: "diamante", aliases: ["joia"] },
  { emoji: "💰", name: "saco de dinheiro", aliases: ["dinheiro"] },
  { emoji: "💵", name: "nota de dinheiro", aliases: ["dolar"] },
  { emoji: "💳", name: "cartao de credito", aliases: ["cartao"] },
  { emoji: "🎁", name: "presente", aliases: [] },
  { emoji: "🎈", name: "balao", aliases: ["bexiga"] },
  { emoji: "🎉", name: "festa", aliases: ["confete"] },
  { emoji: "🎊", name: "bola de confete", aliases: [] },
  { emoji: "🎀", name: "laco", aliases: [] },
  { emoji: "🎃", name: "abobora de halloween", aliases: ["halloween"] },
  { emoji: "🎄", name: "arvore de natal", aliases: ["natal"] },
  { emoji: "💣", name: "bomba", aliases: [] },
  { emoji: "💉", name: "seringa", aliases: ["injecao"] },
  { emoji: "💊", name: "remedio", aliases: ["pilula", "comprimido"] },
  { emoji: "🩺", name: "estetoscopio", aliases: [] },
  { emoji: "🦴", name: "osso", aliases: [] },
  { emoji: "🩸", name: "gota de sangue", aliases: [] },
  { emoji: "🧬", name: "dna", aliases: [] },
  { emoji: "🔬", name: "microscopio", aliases: [] },
  { emoji: "🔭", name: "telescopio", aliases: [] },
  { emoji: "📡", name: "antena", aliases: [] },
  { emoji: "🛰️", name: "satelite", aliases: [] },
  { emoji: "⚓", name: "ancora", aliases: [] },
  { emoji: "🎣", name: "vara de pescar", aliases: ["pescaria"] },
  { emoji: "🪁", name: "pipa", aliases: [] },
  { emoji: "🎨", name: "paleta de tinta", aliases: ["pintura"] },
  { emoji: "🖼️", name: "quadro", aliases: ["pintura emoldurada"] },
  { emoji: "🧸", name: "ursinho de pelucia", aliases: ["ursinho"] },
  { emoji: "🪀", name: "ioio", aliases: [] },
  { emoji: "🧨", name: "rojao", aliases: ["dinamite"] },
  { emoji: "⌚", name: "relogio de pulso", aliases: ["relogio"] },
  { emoji: "⏰", name: "despertador", aliases: [] },
  { emoji: "⏳", name: "ampulheta", aliases: [] },
  { emoji: "📞", name: "telefone", aliases: ["fone"] },
  { emoji: "💼", name: "maleta", aliases: ["pasta executiva"] },
  { emoji: "🔪", name: "faca", aliases: ["faca de cozinha"] },
  { emoji: "🗡️", name: "espada", aliases: [] },
  { emoji: "🛡️", name: "escudo", aliases: [] },
  { emoji: "🪄", name: "varinha magica", aliases: ["varinha"] },
  { emoji: "🧪", name: "tubo de ensaio", aliases: [] },
  { emoji: "💾", name: "disquete", aliases: ["floppy"] },
  { emoji: "💿", name: "cd", aliases: ["disco"] },
  { emoji: "📀", name: "dvd", aliases: [] },
  { emoji: "📦", name: "caixa", aliases: ["pacote"] },
  { emoji: "✉️", name: "envelope", aliases: ["carta"] },
  { emoji: "📜", name: "pergaminho", aliases: [] },
  { emoji: "📰", name: "jornal", aliases: [] },
  { emoji: "🛒", name: "carrinho de compras", aliases: ["carrinho"] },
  { emoji: "🧳", name: "mala", aliases: ["bagagem"] },
  { emoji: "👑", name: "coroa", aliases: [] },
  { emoji: "💍", name: "anel", aliases: ["alianca"] },
  { emoji: "👕", name: "camiseta", aliases: ["blusa"] },
  { emoji: "👖", name: "calca jeans", aliases: ["calca"] },
  { emoji: "👟", name: "tenis esportivo", aliases: ["sapato esportivo"] },
  { emoji: "👞", name: "sapato social", aliases: ["sapato"] },
  { emoji: "👠", name: "salto alto", aliases: ["scarpin"] },
  { emoji: "🧢", name: "bone", aliases: [] },
  { emoji: "🎩", name: "cartola", aliases: [] },
  { emoji: "🩴", name: "chinelo", aliases: ["havaianas"] },
  { emoji: "🛁", name: "banheira", aliases: [] },
  { emoji: "🚽", name: "vaso sanitario", aliases: ["privada", "patente"] },
  { emoji: "🧹", name: "vassoura", aliases: [] },
  { emoji: "🚪", name: "porta", aliases: [] },
  { emoji: "🪑", name: "cadeira", aliases: [] },
  { emoji: "🛏️", name: "cama", aliases: [] },
  { emoji: "🛋️", name: "sofa", aliases: [] },
  { emoji: "🕯️", name: "vela", aliases: [] },
  { emoji: "🧯", name: "extintor", aliases: [] },
  { emoji: "🪥", name: "escova de dentes", aliases: [] },
  { emoji: "🧊", name: "cubo de gelo", aliases: ["gelo"] },

  // --- Symbols ---
  { emoji: "❤️", name: "coracao vermelho", aliases: ["coracao"] },
  { emoji: "💔", name: "coracao partido", aliases: [] },
  { emoji: "💖", name: "coracao brilhante", aliases: [] },
  { emoji: "💯", name: "cem pontos", aliases: ["cem"] },
  { emoji: "✅", name: "marca de check", aliases: ["correto"] },
  { emoji: "❌", name: "x vermelho", aliases: ["errado", "x"] },
  { emoji: "❓", name: "interrogacao", aliases: [] },
  { emoji: "❗", name: "exclamacao", aliases: [] },
  { emoji: "🚫", name: "proibido", aliases: [] },
  { emoji: "☮️", name: "simbolo da paz", aliases: [] },
  { emoji: "♻️", name: "reciclagem", aliases: [] },
  { emoji: "♟️", name: "peao de xadrez", aliases: ["xadrez"] },
  { emoji: "🔔", name: "sino", aliases: [] },
  { emoji: "🔕", name: "sino mudo", aliases: [] },
  { emoji: "🎵", name: "nota musical", aliases: [] },
  { emoji: "🎶", name: "notas musicais", aliases: [] },
  { emoji: "💤", name: "zzz", aliases: ["sono"] },
  { emoji: "💕", name: "dois coracoes", aliases: [] },
  { emoji: "💚", name: "coracao verde", aliases: [] },
  { emoji: "💙", name: "coracao azul", aliases: [] },
  { emoji: "💜", name: "coracao roxo", aliases: [] },
  { emoji: "🖤", name: "coracao preto", aliases: [] },
  { emoji: "💛", name: "coracao amarelo", aliases: [] },
  { emoji: "🧡", name: "coracao laranja", aliases: [] },
  { emoji: "⚠️", name: "aviso", aliases: ["cuidado"] },
  { emoji: "⛔", name: "entrada proibida", aliases: [] },
  { emoji: "🆘", name: "sos", aliases: [] },
  { emoji: "☯️", name: "yin yang", aliases: ["tao"] },
  { emoji: "🔱", name: "tridente", aliases: [] },
  { emoji: "♾️", name: "infinito", aliases: [] },
  { emoji: "▶️", name: "play", aliases: ["tocar"] },
  { emoji: "⏸️", name: "pausa", aliases: [] },
  { emoji: "⏹️", name: "stop", aliases: ["parar"] },
];

// Public catalog as exposed by /api/emoji-list — no metadata that could
// leak the day's pick.
export type PublicEmojiEntry = { emoji: string; name: string };
export const PUBLIC_EMOJI_LIST: PublicEmojiEntry[] = EMOJIS.map(
  ({ emoji, name }) => ({ emoji, name }),
);
